services:
  usersController:
    class: Galleryzr\Users\UsersController
    arguments: ["@usersService"]
  galleriesController:
    class: Galleryzr\Galleries\GalleriesController
    arguments: ["@galleriesService"]