services:
  imagesStorage:
    class: Galleryzr\Images\Service\ImagesStorage
    arguments: ["%storageDirectory.images%"]

  imagesUploadService:
    class: Galleryzr\Images\Service\ImagesUploadService
    arguments: ["@genericRepository", "@imagesStorage"]

  imagesServingService:
    class: Galleryzr\Images\Service\ImagesServingService
    arguments: ["@genericRepository", "@transformationParser", "@imagesStorage"]

  transformationParser:
    class: Galleryzr\Images\Transformation\TransformationParser
